//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSugar.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlackSugar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Bookmarks (stay tuned) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddBookmarks {
            get {
                return ResourceManager.GetString("AddBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add New Tab (Ctrl+T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddNewTab {
            get {
                return ResourceManager.GetString("AddNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bookmarks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContextMenu(beta) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap folder_dark {
            get {
                object obj = ResourceManager.GetObject("folder.dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap folder_light {
            get {
                object obj = ResourceManager.GetObject("folder.light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Folder Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemDate {
            get {
                return ResourceManager.GetString("ItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemPath {
            get {
                return ResourceManager.GetString("ItemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemSize {
            get {
                return ResourceManager.GetString("ItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open SideFiler File...(beta) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save SideFiler File...(beta) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Upper Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MoveUpFolder {
            get {
                return ResourceManager.GetString("MoveUpFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Name: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open with Explorer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenByExplorer {
            get {
                return ResourceManager.GetString("OpenByExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open New Tab に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenNewTab {
            get {
                return ResourceManager.GetString("OpenNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recently Closed Folders...(beta) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RecentlyClosedFolders {
            get {
                return ResourceManager.GetString("RecentlyClosedFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectOpenFile {
            get {
                return ResourceManager.GetString("SelectOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Save File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectSaveFile {
            get {
                return ResourceManager.GetString("SelectSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SETTINGS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tab Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabClose {
            get {
                return ResourceManager.GetString("TabClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateContent {
            get {
                return ResourceManager.GetString("UpdateContent", resourceCulture);
            }
        }
    }
}
